apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
      }
    }

    output {
      elasticsearch {
        hosts => ["http://es-master-service:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.16.2
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.conf
              subPath: logstash.conf
          ports:
            - containerPort: 5044
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash-service
  namespace: elk
spec:
  ports:
    - name: "logstash"
      port: 5044
      targetPort: 5044
  selector:
    app: logstash

